# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 19:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('cfblog', '0006_category_is_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(db_index=True, max_length=255, null=True, blank=True, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^/(?:[-a-zA-Z0-9_]+/)+$'), "Enter a valid 'url path'. Path should start and end with '/'.", 'invalid')], verbose_name='url path'),
        ),
    ]
